### ISSUE TITLE
RAM usage incorrect.

### ISSUE THREAD

**Issue by Entersjkhdfkjdhfksjf** [dockur/umbrel#4]
The RAM usage in umbrel seems to be wrong. Also the docker compose does not seem to be working and I had to use the docker cli command

**Comment by Polygons1** [comment]
> Also the docker compose does not seem to be working and I had to use the docker cli command

same thing here

**Comment by Polygons1** [comment]
umbreld was exiting with a SIGTERM

**Comment by Entersjkhdfkjdhfksjf** [comment]
The ram and cpu usage seem to be completely off. Is there any way to fix it?

**Comment by Polygons1** [comment]
> The ram and cpu usage seem to be completely off. Is there any way to fix it?

I don’t think so, I think this is something related to Docker

**Comment by yoonseokham** [comment]
Hello, I think the resource usage is incorrect. below is the result of the `docker stats`
```console
CONTAINER ID   NAME                          CPU %     MEM USAGE / LIMIT    MEM %     NET I/O           BLOCK I/O         PIDS
dd87e4f622a2   bitcoin-knots_server_1        0.04%     69.98MiB / 15.4GiB   0.44%     14.6MB / 1.73MB   51.8MB / 516kB    23
35a4d42dfbd8   bitcoin-knots_tor_1           3.49%     35.52MiB / 15.4GiB   0.23%     25.4MB / 12.8MB   32.8kB / 24.4MB   1
1cfc55331217   bitcoin-knots_app_proxy_1     0.05%     75.13MiB / 15.4GiB   0.48%     1.2MB / 1.33MB    7.56MB / 8.19kB   19
e8be1cb2996b   bitcoin-knots_bitcoind_1      5.73%     686.4MiB / 15.4GiB   4.35%     803MB / 38.1MB    418MB / 11.2GB    17
0e388ff5147c   bitcoin-knots_i2pd_daemon_1   3.19%     17.79MiB / 15.4GiB   0.11%     41.1MB / 45.5MB   19.9MB / 1.99MB   13
45a06b6531b4   tailscale_web_1               0.23%     49.14MiB / 15.4GiB   0.31%     0B / 0B           41.6MB / 123kB    18
766f371f6ff8   auth                          0.04%     75.69MiB / 15.4GiB   0.48%     4kB / 0B          54.6MB / 8.19kB   19
df8d7fe8bc0c   tor_proxy                     1.32%     39.59MiB / 15.4GiB   0.25%     14.3MB / 1.37MB   7.74MB / 24.4MB   1
b4ad8d7bfae4   fervent_wing                  0.18%     189.6MiB / 15.4GiB   1.20%     1.82MB / 4.7MB    4.72MB / 201MB    39
```
And this is what I got from the live usage page.

![image](https://github.com/user-attachments/assets/325fc1bf-f8fe-484e-b6d4-164f7f4723eb)

Do you why this is happening? I used `dockurr/umbrel:1.3.0-beta.2` image and used docker cli to start up the container

**Comment by btcinsaneguy** [comment]
Hello, I think the resource usage is incorrect. below is the result of the `docker stats`
```console
CONTAINER ID   NAME                          CPU %     MEM USAGE / LIMIT    MEM %     NET I/O           BLOCK I/O         PIDS
dd87e4f622a2   bitcoin-knots_server_1        0.04%     69.98MiB / 15.4GiB   0.44%     14.6MB / 1.73MB   51.8MB / 516kB    23
35a4d42dfbd8   bitcoin-knots_tor_1           3.49%     35.52MiB / 15.4GiB   0.23%     25.4MB / 12.8MB   32.8kB / 24.4MB   1
1cfc55331217   bitcoin-knots_app_proxy_1     0.05%     75.13MiB / 15.4GiB   0.48%     1.2MB / 1.33MB    7.56MB / 8.19kB   19
e8be1cb2996b   bitcoin-knots_bitcoind_1      5.73%     686.4MiB / 15.4GiB   4.35%     803MB / 38.1MB    418MB / 11.2GB    17
0e388ff5147c   bitcoin-knots_i2pd_daemon_1   3.19%     17.79MiB / 15.4GiB   0.11%     41.1MB / 45.5MB   19.9MB / 1.99MB   13
45a06b6531b4   tailscale_web_1               0.23%     49.14MiB / 15.4GiB   0.31%     0B / 0B           41.6MB / 123kB    18
766f371f6ff8   auth                          0.04%     75.69MiB / 15.4GiB   0.48%     4kB / 0B          54.6MB / 8.19kB   19
df8d7fe8bc0c   tor_proxy                     1.32%     39.59MiB / 15.4GiB   0.25%     14.3MB / 1.37MB   7.74MB / 24.4MB   1
b4ad8d7bfae4   fervent_wing                  0.18%     189.6MiB / 15.4GiB   1.20%     1.82MB / 4.7MB    4.72MB / 201MB    39
```
And this is what I got from the live usage page.

![image](https://github.com/user-attachments/assets/325fc1bf-f8fe-484e-b6d4-164f7f4723eb)

Do you why this is happening? I used `dockurr/umbrel:1.3.0-beta.2` image and used docker cli to start up the container

**Comment by btcinsaneguy** [comment]
@kroese 
Im really sure the resource usage is incorrect.
cpu usage is always less than 2%, ram usage is under 200mb. but according to `docker stats` bitcoin-knots uses 686.4MiB alone

**Comment by btcinsaneguy** [comment]
I tried with `umbrel:1.3.0-beta.3` and this is I got
* `docker stats`
![image](https://github.com/user-attachments/assets/4252e513-81ba-458e-9930-fa4a637292d7)
* live usage page
![image](https://github.com/user-attachments/assets/eaa82a5c-c434-46a4-ae87-7a35e3714c8e)

**Comment by btcinsaneguy** [comment]
oh I see. I think inside of umbrel container, it cannot access to host  process using `top`.
maybe adding `--pid=host` could resolve this issue

**Comment by btcinsaneguy** [comment]
@kroese 
sounds good I will add that as well

**Comment by btcinsaneguy** [comment]
great.
`--pid=host` resolved the cpu usage issue but ram usage was same.
`--privileged` flag resolved the ram usage issue
so I think we need both flag for each cpu and ram usage to be correctly displayed
thanks for the help
![image](https://github.com/user-attachments/assets/72ca976c-a4ee-450c-8680-00a3870d7a37)

**Comment by btcinsaneguy** [comment]
@kroese I used 1.3.0 and it worked without `--privileged`
